# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name h8labeling.com www.h8labeling.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name h8labeling.com www.h8labeling.com;

    ssl_certificate /etc/letsencrypt/live/h8labeling.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/h8labeling.com/privkey.pem;

    # Frontend
    location / {
        proxy_pass http://frontend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    # Backend API
    location /api/ {
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 2G;
    }
}
